import { jsPDF } from "jspdf";
import { state, DATA, monthTx, monthLabel, totals } from "./state.js";
import { catInfo } from "./categories.js";
import { fmt } from "./format.js";

// A simple one-page PDF statement for the currently viewed month — separate
// from the CSV export (which is raw transaction rows for a spreadsheet) and
// the JSON backup (which is for restoring into Kwenta itself). This one is
// for handing to someone else: a partner, a family member, anyone who wants
// a readable summary without opening the app.
export function exportMonthlyStatementPDF() {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 14;
  let y = 20;

  const t = totals();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Kwenta", marginX, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(90);
  doc.text(`Monthly statement — ${monthLabel(state.monthKey)}`, marginX, y + 7);
  doc.setTextColor(0);
  y += 20;

  doc.setDrawColor(210);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 10;

  // ── Summary ──
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Summary", marginX, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Income", marginX, y);
  doc.text(fmt(t.totalIncome), 90, y);
  y += 7;
  doc.text("Expenses", marginX, y);
  doc.text(fmt(t.totalExpense), 90, y);
  y += 7;
  doc.setFont("helvetica", "bold");
  doc.text("Net balance", marginX, y);
  const balanceLabel = (t.balance < 0 ? "-" : "") + fmt(Math.abs(t.balance));
  if (t.balance < 0) doc.setTextColor(220, 38, 65);
  doc.text(balanceLabel, 90, y);
  doc.setTextColor(0);
  y += 14;

  // ── Expenses by category ──
  const exp = monthTx("expense");
  const byCat = {};
  exp.forEach((e) => {
    byCat[e.category] = (byCat[e.category] || 0) + Number(e.amount || 0);
  });
  const entries = Object.entries(byCat).sort((a, b) => b[1] - a[1]);

  if (entries.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text("Expenses by category", marginX, y);
    y += 9;

    doc.setFontSize(10.5);
    entries.forEach(([catId, amt]) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      const label = catInfo(catId).label;
      const budget = Number(DATA.budgets[catId]) || 0;
      const over = budget > 0 && amt > budget;

      doc.setFont("helvetica", "normal");
      doc.setTextColor(0);
      doc.text(label, marginX, y);
      doc.text(fmt(amt), 90, y);

      if (budget > 0) {
        doc.setFontSize(9);
        doc.setTextColor(over ? 220 : 140, over ? 38 : 140, over ? 65 : 140);
        doc.text(`of ${fmt(budget)} budgeted${over ? " — over" : ""}`, 120, y);
        doc.setTextColor(0);
        doc.setFontSize(10.5);
      }
      y += 7;
    });
    y += 6;
  }

  // ── Upcoming bills (only if there are any, and only for the real current month) ──
  if (DATA.bills.length > 0) {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }
    doc.setDrawColor(210);
    doc.line(marginX, y, pageWidth - marginX, y);
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text("Bills on file", marginX, y);
    y += 9;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    DATA.bills.forEach((bill) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(bill.name, marginX, y);
      doc.text(`Due on the ${bill.dueDay}${ordinalSuffix(bill.dueDay)}`, 90, y);
      if (bill.estimatedAmount) {
        doc.text(`~${fmt(bill.estimatedAmount)}`, 150, y);
      }
      y += 7;
    });
    y += 6;
  }

  // ── Footer ──
  doc.setDrawColor(210);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 8;
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text(
    `Generated by Kwenta on ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`,
    marginX,
    y,
  );

  doc.save(`kwenta-statement-${state.monthKey}.pdf`);
}

function ordinalSuffix(n) {
  if (n % 10 === 1 && n % 100 !== 11) return "st";
  if (n % 10 === 2 && n % 100 !== 12) return "nd";
  if (n % 10 === 3 && n % 100 !== 13) return "rd";
  return "th";
}
